SYMBOL_COUNT = 16000
BITS_PER_SYMBOL = 16
MEMORY_IN_BITS = SYMBOL_COUNT * BITS_PER_SYMBOL
MEMORY_IN_MB = MEMORY_IN_BITS / (8 * 1000 * 1000)
MEMORY_IN_MIB = MEMORY_IN_BITS / (8 * 1024 * 1024)

print(f"Der Speicherbedarf beträgt {MEMORY_IN_MB:.2f} MB oder {MEMORY_IN_MIB:.2f} MiB.")

LENGHT_AUDIO_SECONDS = 60
BITS_PER_SECOND = 44100 * 16
AUDIO_MEMORY_IN_BITS = LENGHT_AUDIO_SECONDS * BITS_PER_SECOND
AUDIO_MEMORY_IN_MB = AUDIO_MEMORY_IN_BITS / (8 * 1000 * 1000)
AUDIO_MEMORY_IN_MIB = AUDIO_MEMORY_IN_BITS / (8 * 1024 * 1024)

print(
    f"Der Speicherbedarf für eine Minute Audio beträgt {AUDIO_MEMORY_IN_MB:.2f} MB oder {AUDIO_MEMORY_IN_MIB:.2f} MiB."
)

PIXEL_COUNT = 8000 * 8000
BITS_PER_PIXEL = 32
IMAGE_MEMORY_IN_BITS = PIXEL_COUNT * BITS_PER_PIXEL
IMAGE_MEMORY_IN_MB = IMAGE_MEMORY_IN_BITS / (8 * 1000 * 1000 * 1000)
IMAGE_MEMORY_IN_MIB = IMAGE_MEMORY_IN_BITS / (8 * 1024 * 1024 * 1024)

print(
    f"Der Speicherbedarf für ein 8000x8000 Pixel großes Bild beträgt {IMAGE_MEMORY_IN_MB:.2f} GB oder {IMAGE_MEMORY_IN_MIB:.2f} GiB."
)
