import time
from datetime import datetime

from PySide6.QtCore import Qt, QTimer
from PySide6.QtGui import QKeyEvent, QMouseEvent, QPainter, QPaintEvent
from PySide6.QtWidgets import QApplication, QMainWindow


class BaseWindow(QMainWindow):
    """
    BaseWindow is a QMainWindow subclass providing a framework for simple
    real-time GUI applications with frame timing, mouse, and keyboard event handling.

    Attributes:
        frame (int): Current frame count.
        frameRate (float): Current target frame rate pre second (up to 1000 Hz).
        fps (float): Calculated frames per second (averaged every second).
        leftButtonPressed (bool): Status of the left mouse button.
        rightButtonPressed (bool): Status of the right mouse button.
        mousePos: Current mouse position.
        pMousePos: Previous mouse position.
        keyPressed (bool): Whether a key is currently pressed.
        keyCode: Code of the currently pressed key.
        keyText: Unicode text generated by the current key press.

    Versions:
        2025-05-18 | swiest | 1.0.0 | Initial version.
        2025-05-22 | swiest | 1.1.1 | Introduced setup() and draw().
        2025-05-31 | swiest | 1.2.0 | Removed debugging outputs. Quit app on ESC key.
        2025-10-26 | swiest | 1.2.1 | Changed to high precision timer.
        2025-12-05 | swiest | 1.2.2 | Changed Qt enum constants from unscoped to enum scoped.
    """

    def __init__(self, width, height, title):
        super().__init__()

        self.setGeometry(100, 100, width, height)
        self.setWindowTitle(title)

        self._startFrame = 0
        self._appStartTime = time.perf_counter()
        self._startTime = self._appStartTime
        self.frameCount = 0
        self.frameRate = 60  # 60 Hz default
        self.fps = 0

        self.leftButtonPressed = False  # To store the current left button status
        self.rightButtonPressed = False  # To store the current right button status
        self.mousePos = None  # To store the current mouse position
        self.pMousePos = None  # To store the previous current mouse position
        self.keyPressed = False  # To store the previous current mouse position
        self.keyCode = None  # Most recent key pressed, see Qt.Key
        self.keyText = None  # Unicode text that the most recent key pressed generated

        # Set up a timer to trigger paintEvent 60 times per second
        self.timer = QTimer(self)
        self.timer.setTimerType(Qt.TimerType.PreciseTimer)
        self.timer.timeout.connect(self.update)
        self.timer.start(1000 // self.frameRate)
        self.setMouseTracking(True)

        self.setup()  # Delegating to child class

    def paint(self, p: QPainter):
        """Emtpy implementation. To be overridden by child class."""
        ...

    def setup(self):
        """Emtpy implementation. To be overridden by child class."""
        ...

    def paintEvent(self, event: QPaintEvent) -> None:
        delta_time = time.perf_counter() - self._startTime

        if delta_time > 1:  # one second
            self.fps = (self.frameCount - self._startFrame) / delta_time
            self._startFrame = self.frameCount
            self._startTime = time.perf_counter()

        p = QPainter(self)
        p.setRenderHint(QPainter.RenderHint.Antialiasing)
        p.setRenderHint(QPainter.RenderHint.SmoothPixmapTransform)

        self.paint(p)  # Delegate to child class

        self.frameCount += 1

    def setFrameRate(self, frame_rate: float):
        self.frameRate = frame_rate
        self.timer.setInterval(1000 // int(frame_rate))

    def keyPressEvent(self, event: QKeyEvent):
        self.keyCode = event.key()
        self.keyText = event.text()
        self.keyPressed = True

        # Quit the application if the ESC key is pressed. Useful to quit in full screen modes.
        if self.keyCode == Qt.Key.Key_Escape:
            print("Quitting application on escape key...")
            QApplication.quit()

    def keyReleaseEvent(self, event: QKeyEvent):
        self.keyPressed = None

    def mousePressEvent(self, event):
        self.leftButtonPressed = (
            True if event.button() == Qt.MouseButton.LeftButton else False
        )
        self.rightButtonPressed = (
            True if event.button() == Qt.MouseButton.RightButton else False
        )

    def mouseReleaseEvent(self, event):
        self.leftButtonPressed = (
            False if event.button() == Qt.MouseButton.LeftButton else True
        )
        self.rightButtonPressed = (
            True if event.button() == Qt.MouseButton.RightButton else False
        )

    def mouseMoveEvent(self, event: QMouseEvent):
        self.pMousePos = self.mousePos
        self.mousePos = event.position()

    def year(self) -> int:
        return datetime.now().year

    def month(self) -> int:
        return datetime.now().month

    def day(self) -> int:
        return datetime.now().day

    def hours(self) -> int:
        return datetime.now().hour

    def minutes(self) -> int:
        return datetime.now().minute

    def seconds(self) -> int:
        return datetime.now().second

    def microseconds(self) -> int:
        return datetime.now().microsecond

    def elapsed(self) -> float:
        """Seconds elapsed since start of application."""
        return time.perf_counter() - self._appStartTime


def launch(
    clazz: type[BaseWindow], width: int = 400, height: int = 300, title: str = ""
):
    app = QApplication()
    window = clazz(width, height, title)
    window.show()
    app.exec()
